# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

  # Allows manual execution from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # ✅ Allows pushing changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v2
        with:
          github_user_name: manishalama123
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
