# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

  # Allows manual execution from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # ✅ Allows pushing changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/

  # Deployment Job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-animation
          path: dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # This is where the snake animation will be deployed
          folder: dist       # Deploy the `dist/` folder
